### ISSUE TITLE
Remove client secret from logs

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxd#202]
![image](https://user-images.githubusercontent.com/3717101/41501324-e3bd1ab8-7167-11e8-9d82-882a3539f064.png)

**Comment by yuriyz** [comment]
done for 3.1.4 and 4.0.0

**Comment by natt-tester** [comment]
Checked in 3.1.4, client_secret is still present in the logs:
<img width="1045" alt="client_secret_present" src="https://user-images.githubusercontent.com/38302725/46796310-153f6780-cd98-11e8-863e-8b8f86e06261.png">
[oxd-server.log.tar.gz](https://github.com/GluuFederation/oxd/files/2468396/oxd-server.log.tar.gz)

**Comment by yuriyz** [comment]
thanks, I will fix it

**Comment by yuriyz** [comment]
@natt-tester fixed in 3.1.4

**Comment by natt-tester** [comment]
Checked in 3.1.4: it's fixed.
