### ISSUE TITLE
apt-get remove oxd-server in Debian 8 doesn't kill oxd or extension

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#250]
```
root@osboxes:/opt/oxd-server/bin# apt-get remove oxd-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  oxd-server
0 upgraded, 0 newly installed, 1 to remove and 310 not upgraded.
After this operation, 102 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 133706 files and directories currently installed.)
Removing oxd-server (3.1.4-25~jessie+Db8) ...
root@osboxes:/opt/oxd-server/bin# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      375/rpcbind     
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      785/exim4       
tcp        0      0 0.0.0.0:59902           0.0.0.0:*               LISTEN      390/rpc.statd   
tcp6       0      0 127.0.0.1:8099          :::*                    LISTEN      3992/java       
tcp6       0      0 :::33963                :::*                    LISTEN      390/rpc.statd   
tcp6       0      0 :::111                  :::*                    LISTEN      375/rpcbind     
tcp6       0      0 ::1:25                  :::*                    LISTEN      785/exim4       
tcp6       0      0 :::8443                 :::*                    LISTEN      4177/java       
tcp6       0      0 :::8444                 :::*                    LISTEN      4177/java       
udp        0      0 0.0.0.0:43916           0.0.0.0:*                           390/rpc.statd   
udp        0      0 0.0.0.0:971             0.0.0.0:*                           375/rpcbind     
udp        0      0 127.0.0.1:990           0.0.0.0:*                           390/rpc.statd   
udp        0      0 10.0.2.15:44046         0.0.0.0:*                           1477/dleyna-rendere
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           424/avahi-daemon: r
udp        0      0 0.0.0.0:48379           0.0.0.0:*                           424/avahi-daemon: r
udp        0      0 0.0.0.0:25983           0.0.0.0:*                           592/dhclient    
udp        0      0 127.0.0.1:38360         0.0.0.0:*                           1477/dleyna-rendere
udp        0      0 239.255.255.250:1900    0.0.0.0:*                           1477/dleyna-rendere
udp        0      0 10.0.2.15:1900          0.0.0.0:*                           1477/dleyna-rendere
udp        0      0 239.255.255.250:1900    0.0.0.0:*                           1477/dleyna-rendere
udp        0      0 127.0.0.1:1900          0.0.0.0:*                           1477/dleyna-rendere
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           483/minissdpd   
udp        0      0 0.0.0.0:68              0.0.0.0:*                           592/dhclient    
udp        0      0 0.0.0.0:111             0.0.0.0:*                           375/rpcbind     
udp6       0      0 :::53865                :::*                                592/dhclient    
udp6       0      0 :::49941                :::*                                390/rpc.statd   
udp6       0      0 :::971                  :::*                                375/rpcbind     
udp6       0      0 :::5353                 :::*                                424/avahi-daemon: r
udp6       0      0 :::32832                :::*                                424/avahi-daemon: r
udp6       0      0 :::111                  :::*                                375/rpcbind     
```

**Comment by nikdavnik** [comment]
Fixed in new build

**Comment by natt-tester** [comment]
Hm... is the new build already in the repo? The new package has Yuriy's change, but still the same issue with ```remove``` and ```purge```:
```
root@osboxes:/opt/oxd-server/bin# apt-get purge oxd-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  oxd-server*
0 upgraded, 0 newly installed, 1 to remove and 238 not upgraded.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 133684 files and directories currently installed.)
Removing oxd-server (3.1.4-26~jessie+Db8) ...
Purging configuration files for oxd-server (3.1.4-26~jessie+Db8) ...
dpkg: warning: while removing oxd-server, directory '/opt/oxd-https-extension' not empty so not removed
dpkg: warning: while removing oxd-server, directory '/opt/oxd-server/bin' not empty so not removed
root@osboxes:/opt/oxd-server/bin# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:53220           0.0.0.0:*               LISTEN      385/rpc.statd   
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      370/rpcbind     
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      771/exim4       
tcp6       0      0 :::53154                :::*                    LISTEN      385/rpc.statd   
tcp6       0      0 127.0.0.1:8099          :::*                    LISTEN      3327/java       
tcp6       0      0 :::111                  :::*                    LISTEN      370/rpcbind     
tcp6       0      0 ::1:25                  :::*                    LISTEN      771/exim4       
tcp6       0      0 :::8443                 :::*                    LISTEN      3527/java       
tcp6       0      0 :::8444                 :::*                    LISTEN      3527/java       
udp        0      0 0.0.0.0:55959           0.0.0.0:*                           385/rpc.statd   
udp        0      0 0.0.0.0:51957           0.0.0.0:*                           422/avahi-daemon: r
udp        0      0 0.0.0.0:969             0.0.0.0:*                           370/rpcbind     
udp        0      0 127.0.0.1:985           0.0.0.0:*                           385/rpc.statd   
udp        0      0 0.0.0.0:5353            0.0.0.0:*           
```

**Comment by nikdavnik** [comment]
fixed, please check the new package

**Comment by natt-tester** [comment]
Done in the latest package.
