### ISSUE TITLE
NPE while using lsox script

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxd#280]
Steps:

1. In a fresh installation **with running oxd**, go to /opt/oxd-server/bin
2. Enter `sh lsox.sh -oxd_idv3vnn -a vevve3e` (or other two malformed arguments)
3. Press Enter

Expected: There should be a message saying that the arguments aren't recognized.
Actual: There's an Internal Server Error (500) displayed with a NPE in the logs:

```
[root@localhost bin]# sh lsox.sh -oxd_id cwcwvwww -a cwvcwvwvw
BASEDIR=/opt/oxd-server
CONF=/opt/oxd-server/conf/oxd-server.yml
Failed to execute command against oxd-server on port Pair{first=8443, second=true}, error: HTTP 500 Internal Server Error
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
    at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1032)
    at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
    at org.glassfish.jersey.client.JerseyInvocation.access$800(JerseyInvocation.java:92)
    at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:724)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:720)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:459)
    at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:343)
    at com.sun.proxy.$Proxy41.getRp(Unknown Source)
    at org.xdi.oxd.server.Cli.tryToConnectToRunningOxd(Cli.java:231)
    at org.xdi.oxd.server.Cli.main(Cli.java:104)
[root@localhost bin]# sh lsox.sh -l cwcwvwww -a cwvcwvwvw
BASEDIR=/opt/oxd-server
CONF=/opt/oxd-server/conf/oxd-server.yml
oxd_id                                client_name
cd037f74-26e9-4295-816c-90adac5f1225  tom2
7d6d2ba1-41c1-4ca5-aa82-22ad4fed0237  tom1
3b063af1-55c8-46cc-84af-f5c7ca32a1b9  tom3
70a8bcde-3fd0-403d-b55a-d56ebee44f26  null
d92c2667-6d76-4fbd-83c4-fb3df7ca44dc  null
[root@localhost bin]# sh lsox.sh -l cwcwvwww 
BASEDIR=/opt/oxd-server
CONF=/opt/oxd-server/conf/oxd-server.yml
Failed to connect to running oxd. There are two ways to proceed: 
 - 1) stop oxd and then run command again. Then script can connect to database directly. If oxd is running it has exclusive lock on database, so script is not able to connect to database directly
 - 2) provide authorization access_token (same that is provided in Authorization header in oxd API) via -a parameter (e.g. lsox.sh -a xxxx-xxxx-xxxx-xxxx -l), so script can connect to running oxd
[root@localhost bin]# sh lsox.sh -l cwcwvwww -a cwvcwvwvw
BASEDIR=/opt/oxd-server
CONF=/opt/oxd-server/conf/oxd-server.yml
oxd_id                                client_name
cd037f74-26e9-4295-816c-90adac5f1225  tom2
7d6d2ba1-41c1-4ca5-aa82-22ad4fed0237  tom1
3b063af1-55c8-46cc-84af-f5c7ca32a1b9  tom3
70a8bcde-3fd0-403d-b55a-d56ebee44f26  null
d92c2667-6d76-4fbd-83c4-fb3df7ca44dc  null
```

**Confirmed in both Ubuntu 14 4.0beta and Centos6 3.1.4 -> 4.0beta migration.**
[oxd-server(2).log](https://github.com/GluuFederation/oxd/files/2627378/oxd-server.2.log)

**Comment by duttarnab** [comment]
This issue was due to incorrect token_id or oxd_id in command and have been fixed in oxd version_4.0 branch.

**Comment by yuriyz** [comment]
This issue is not fixed. We got 500 which is internal error. oxd has to indentify bad parameters and return 400 (bad request). If script faces 400 then it should say that parameters should be checked.

**Comment by yuriyz** [comment]
Fixed by https://github.com/GluuFederation/oxd/pull/314
