### ISSUE TITLE
update-site api not updating field values using oxd-4.0

### ISSUE THREAD

**Issue by sobhanpanda** [GluuFederation/oxd#296]
/update-site api not updating the values for the following fields:
authorization_redirect_uri, claims_redirect_uri, acr_values, client_name, client_secret_expires_at

**Comment by MohitMaliFtechiz** [comment]
@sobhanpanda Please recheck the issue, when tried to /update-site api with oxd_4.0 its working and giving oxd id in response.
request :
{
  "oxd_id": "f1378965-6141-43de-aba3-1a53a96e4de9",
  "authorization_redirect_uri": "https://client.example.org/cb",
  "client_name" : "Test2",
  "client_secret_expires_at" : 600,
  "claims_redirect_uri" : "https://client.example.org/cb",
  "acr_values" : ["basic"]
  }         

response:
{"oxd_id":"f1378965-6141-43de-aba3-1a53a96e4de9"}

**Comment by sobhanpanda** [comment]
@MohitMaliFtechiz  /update-site api is giving oxd_id in response. But the values are not updated.

Some values are only updated in oxd DB and not updated in Gluu DB. Like authorization_redirect_uri.
And some values are not updated both in oxd and Gluu DB. Like claims_redirect_uri, acr_values..

**Comment by yuriyz** [comment]
- `authorization_redirect_uri` is updated, it is added as `redirect_uris` to the client (on AS side).
- `claims_redirect_uri` - there is no such parameter in `/update-site` command (see https://gluu.org/docs/oxd/4.0/api)
- `client_name` - no such parameter in `/update-site` command 
- `client_secret_expires_at` - it was removed since it produces security issues on AS.

So overall it is not bug. However from other side we can consider it as feature request if we want to add support for `client_name` or `claims_redirect_uri` parameters.

**Comment by sobhanpanda** [comment]
Thanks @yuriyz for your comments. Today I took the latest oxd 4.0 and tested it. Please find my feedback below.

1- What is difference between authorization_redirect_uri and redirect_uris in oxd_db?
2- Update authorization_redirect_uri from oxd does not update Redirect Login URIs in Gluu server.
3- Update acr_values from oxd server does not update acr_values in oxd_db and Gluu server.
4- If client_secret_expires_at is not required, then can we remove it from oxd-server DB? If we extend the client_secret_expires_at in Gluu server (oxTrust) that does not update oxd server DB. So for the client application which expiry date will be considered? oxd DB expiry date or Gluu server expiry date.

As I mentioned above authorization_redirect_uri does not update Redirect Login URIs in Gluu server and also the acr_values in Gluu server. You may need to check for other fields also. If you are not able to reproduce the issues, let me know I will share a screen recording.

Environment: oxd 4.0, Gluu 3.1.5, Ubuntu 16.04

**Comment by ldeveloperl1985** [comment]
Yes, it is not updating in my case. Also one more bug, At the time of update it removing `client_credentials` grant from my op client even i am not passing `grant_types` in update request

**Comment by yuriyz** [comment]
@sobhanpanda 

> 1- What is difference between authorization_redirect_uri and redirect_uris in oxd_db?

RP/Client can have many `redirect_uris`. however during authn&authz (via `get-authorization-url`) it can be redirected to exactly one. So there can be many `redirect_uris` and by `authorization_redirect_uri` we specify to which exactly user will be redirected. (See also this ticket to be able choose redirect uri between `redirect_uris` https://github.com/GluuFederation/oxd/issues/308)

> 2- Update authorization_redirect_uri from oxd does not update Redirect Login URIs in Gluu server.

I'm not able to reproduce it. I've added test which confirms that it works (org.gluu.oxd.server.UpdateSiteTest#update, https://github.com/GluuFederation/oxd/blob/64c37baafd6db025b6f5adb3f922df82a299bcb1/oxd-server/src/test/java/org/gluu/oxd/server/UpdateSiteTest.java#L40)

> 3- Update acr_values from oxd server does not update acr_values in oxd_db and Gluu server.

Confirmed/reproducible, fixed in `version_4.0` branch. Added test for it.

> 4- If client_secret_expires_at is not required, then can we remove it from oxd-server DB? If we extend the client_secret_expires_at in Gluu server (oxTrust) that does not update oxd server DB. So for the client application which expiry date will be considered? oxd DB expiry date or Gluu server expiry date.

CE/OP always win. Indeed if you manually update any value in LDAP (via oxtrust or ldap client) then oxd will not reflect it. oxd knows only about data which are updated via oxd. re: `client_secret_expires_at`, this value is returned according to Connect spec. We don't use it by oxd but maybe we will want to use it in future, so we keep it for now (https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationResponse).

Below if screen of client entry after update as well as logs of `UpdateSiteTest.update` test.

![image](https://user-images.githubusercontent.com/2013070/56132681-4ab94d80-5f93-11e9-8f12-3dadaef9eff0.png)

[UpdateSiteTest.update.txt](https://github.com/GluuFederation/oxd/files/3080105/UpdateSiteTest.update.txt)

If something from above does not work for you, please attach:

- log from (UpdateSiteTest.update())
- ldif of client from CE



-

**Comment by yuriyz** [comment]
@ldeveloperl1985 re: `grant_types` update. It is special case because it's handled by OP depending on what is set in `response_type`. See this logic coded by Javier:

https://github.com/GluuFederation/oxAuth/blob/a8ece918e4db6c2016e878c92cb18e77747327ec/Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java#L327

So theoretically if you set `client_credentials` and then changed your `response_type` then yes, `client_credentials` can be cleared and it's expected behavior for now. If we want to change OP handling then we can discuss it.

**Comment by yuriyz** [comment]
Fixed in `version_4.0` branch.

**Comment by yuriyz** [comment]
added note to docs about `response_types` and `grant_types` handling https://github.com/GluuFederation/docs-oxd-prod/commit/8559cdffbcce8b8d2842c9934420d2e4f5fbc9cd

**Comment by sobhanpanda** [comment]
Hi @yuriyz I am still having issue.

1- Installed the latest oxd-server.

2- I created a client using /register-site api.
![image](https://user-images.githubusercontent.com/20181885/56578672-d2363a80-65eb-11e9-88f9-dbcbfee3f949.png)

3- Fetched token using /get-client-token api.
![image](https://user-images.githubusercontent.com/20181885/56578814-2b05d300-65ec-11e9-8755-eb912ebe45e3.png)

4- Updated the client using /update-site api. Its returning oxd_id in response.
![image](https://user-images.githubusercontent.com/20181885/56578956-80da7b00-65ec-11e9-8e30-73f2a266f6a5.png)

I checked the oxd_db and found acr_value is not updated.
![image](https://user-images.githubusercontent.com/20181885/56579320-81274600-65ed-11e9-8cad-e4c16e883bf2.png)

Also, its not updated in Gluu server.
![image](https://user-images.githubusercontent.com/20181885/56579465-d5cac100-65ed-11e9-835d-822319d7e713.png)


Next, I tried to fetch the token using /get-client-token api for the same client, but its throwing error.
![image](https://user-images.githubusercontent.com/20181885/56579618-496cce00-65ee-11e9-8e32-cfb23aebbb54.png)

Attached the oxd-server and oxauth logs.
[oxd-server.log](https://github.com/GluuFederation/oxd/files/3107416/oxd-server.log)
[oxauth.log](https://github.com/GluuFederation/oxd/files/3107417/oxauth.log)

**Comment by yuriyz** [comment]
@sobhanpanda according to log you are using 2 month old oxd-server while this ticket was fixed 8 days ago. Please take oxd 4.0 server from our maven repo https://ox.gluu.org/maven/org/gluu/oxd-server/4.0-SNAPSHOT/oxd-server-4.0-SNAPSHOT-distribution.zip
